# docker-compose dev.yaml
version: "2"
services:
  lib:
    build: "./"
    image: "charandas/schema-survey-data"
    volumes:
      - .:/src
    depends_on:
      - rethink
  rethink:
    image: "charandas/rethinkdb:2.3.5"
    ports:
     - "8081:8080"
