# docker-compose dev.yaml
version: "3.1"
services:
  lib:
    build: "./"
    image: "charandas/schema-survey-data"
    volumes:
      - .:/src
   depends_on:
     - rethink
    command: /bin/sh
    stdin_open: true
    tty: true
  rethink:
    image: "charandas/rethinkdb:2.3.5"
    ports:
     - "8081:8080"
